import Home from '@/components/Home/Home'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.css'

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} `}>
          <Home />
      </main>

    </div>
  )
}
